---
version: '3.7'
services:
  nginx:
    environment:
      USE_TLS: 'true'
      GENERATE_TLS_CERTIFICATE: 'true'
      DD_PORT: ${DD_PORT:-8080}
      DD_TLS_PORT: ${DD_TLS_PORT:-8443}
  uwsgi:
    environment:
      DD_SESSION_COOKIE_SECURE: 'True'
      DD_CSRF_COOKIE_SECURE: 'True'
